name: Build Docker Image
on:
  push:
    branches:
      - main
      - dev
      - feature/*
  workflow_dispatch:

env:
  JSBASEURL: https://github.com/static/js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set branch name env var
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Set image name env var
        shell: bash
        run: |
          protected=("main" "dev")
          if [[ ${protected[@]} =~ "$BRANCH_NAME" ]]; then
            echo "IMAGE_NAME=ghcr.io/theanadimukt/learn-github-actions" >> $GITHUB_ENV
          else
            echo "IMAGE_NAME=ghcr.io/theanadimukt/learn-github-actions-$BRANCH_NAME" >> $GITHUB_ENV
          fi

      - name: Set JS base url env
        shell: bash
        run: |
          if [[ "$BRANCH_NAME" = 'dev' ]]; then
            printf 'inside dev %s \n' "$BRANCH_NAME"
            echo "JSBASEURL=https://github.dev.com/static/js" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" = 'feature-test' ]]; then
            printf 'inside else feature-test %s \n' "$BRANCH_NAME"
            echo "JSBASEURL=https://github.feature-test.com/static/js" >> $GITHUB_ENV
          fi
      

      - name: Print vars
        shell: bash
        run: |
          printf '%s\n' "$BRANCH_NAME"
          printf '%s\n' "$IMAGE_NAME"
          printf '%s\n' "$JSBASEURL"
